export const THEMES = {
  bollywood: {
    name: 'Bollywood Frames',
    titleText: 'BOLLYWOOD',
    colors: {
      primary: '#D4AF37',
      primaryLight: '#F4D03F',
      primaryDark: '#B8860B',
      accent: '#E91E63',
      accentDark: '#880E4F',
      secondary: '#00BFA5',
      bgDark: '#0D0208',
      bgMid: '#1A0A14',
      bgLight: '#150520',
      textLight: '#FFF8E7',
      textDark: '#1A0A14',
    },
    imageFolder: 'images',
    teamNames: [
      ['Shahenshah', 'Mogambo'],
      ['Dilwale', 'Dulhania'],
      ['Munna', 'Circuit'],
      ['Jai', 'Veeru'],
      ['Rahul', 'Anjali'],
      ['Chulbul', 'Pandey'],
      ['Gabbar', 'Thakur'],
      ['Don', 'Jaani'],
    ],
    winnerPhrases: [
      'Picture abhi baaki hai mere dost... oh wait, you won!',
      'Rishte mein toh hum tumhare baap lagte hain... CHAMPIONS!',
      'Vijay Dinanath Chauhan... WINNER!',
    ],
    loserPhrases: [
      'Mogambo khush nahi hua!',
      'Kabhi kabhi jeetne ke liye kuch haarna padta hai',
      'Haar kar jeetne wale ko baazigar kehte hain... but not today!',
    ],
  },
  hollywood: {
    name: 'Hollywood Frames',
    titleText: 'HOLLYWOOD',
    colors: {
      primary: '#C0C0C0',
      primaryLight: '#E8E8E8',
      primaryDark: '#A0A0A0',
      accent: '#FF4444',
      accentDark: '#CC0000',
      secondary: '#4169E1',
      bgDark: '#0A0A0A',
      bgMid: '#1A1A2E',
      bgLight: '#16213E',
      textLight: '#FFFFFF',
      textDark: '#1A1A2E',
    },
    imageFolder: 'images_hollywood',
    teamNames: [
      ['Avengers', 'Justice League'],
      ['Marvel', 'DC'],
      ['Jedi', 'Sith'],
      ['Bond', 'Bourne'],
      ['Hogwarts', 'Mordor'],
      ['Gotham', 'Metropolis'],
      ['Rebels', 'Empire'],
      ['Autobots', 'Decepticons'],
    ],
    winnerPhrases: [
      "I'll be back... as champion!",
      'You had me at hello... WINNER!',
      'May the Force be with you, champion!',
      "Here's looking at you, WINNER!",
      'To infinity and beyond... CHAMPIONS!',
    ],
    loserPhrases: [
      'Hasta la vista, baby!',
      "You can't handle the truth!",
      "Here's looking at you, kid... better luck next time!",
      'I am inevitable... your loss!',
      "Frankly, my dear, I don't give a damn about your score!",
    ],
  },
}
