export const THEMES = {
  bollywood: {
    name: 'Bollywood Frames',
    titleText: 'BOLLYWOOD',
    colors: {
      primary: '#D4AF37',
      primaryLight: '#F4D03F',
      primaryDark: '#B8860B',
      accent: '#E91E63',
      accentDark: '#880E4F',
      secondary: '#00BFA5',
      bgDark: '#0D0208',
      bgMid: '#1A0A14',
      bgLight: '#150520',
      textLight: '#FFF8E7',
      textDark: '#1A0A14',
    },
    categoryLabel: 'Movie',
    categoryLabelPlural: 'Movies',
    gameTitle: 'GUESS THE MOVIE',
    subtitle: 'THE ULTIMATE MOVIE GUESSING GAME',
    imageFolder: 'images',
    teamNames: [
      ['Shahenshah', 'Mogambo'],
      ['Dilwale', 'Dulhania'],
      ['Munna', 'Circuit'],
      ['Jai', 'Veeru'],
      ['Rahul', 'Anjali'],
      ['Chulbul', 'Pandey'],
      ['Gabbar', 'Thakur'],
      ['Don', 'Jaani'],
    ],
    winnerPhrases: [
      'Picture abhi baaki hai mere dost... oh wait, you won!',
      'Rishte mein toh hum tumhare baap lagte hain... CHAMPIONS!',
      'Vijay Dinanath Chauhan... WINNER!',
    ],
    loserPhrases: [
      'Mogambo khush nahi hua!',
      'Kabhi kabhi jeetne ke liye kuch haarna padta hai',
      'Haar kar jeetne wale ko baazigar kehte hain... but not today!',
    ],
  },
  hollywood: {
    name: 'Hollywood Frames',
    titleText: 'HOLLYWOOD',
    colors: {
      primary: '#C0C0C0',
      primaryLight: '#E8E8E8',
      primaryDark: '#A0A0A0',
      accent: '#FF4444',
      accentDark: '#CC0000',
      secondary: '#4169E1',
      bgDark: '#0A0A0A',
      bgMid: '#1A1A2E',
      bgLight: '#16213E',
      textLight: '#FFFFFF',
      textDark: '#1A1A2E',
    },
    categoryLabel: 'Movie',
    categoryLabelPlural: 'Movies',
    gameTitle: 'GUESS THE MOVIE',
    subtitle: 'THE ULTIMATE MOVIE GUESSING GAME',
    imageFolder: 'images_hollywood',
    teamNames: [
      ['Avengers', 'Justice League'],
      ['Marvel', 'DC'],
      ['Jedi', 'Sith'],
      ['Bond', 'Bourne'],
      ['Hogwarts', 'Mordor'],
      ['Gotham', 'Metropolis'],
      ['Rebels', 'Empire'],
      ['Autobots', 'Decepticons'],
    ],
    winnerPhrases: [
      "I'll be back... as champion!",
      'You had me at hello... WINNER!',
      'May the Force be with you, champion!',
      "Here's looking at you, WINNER!",
      'To infinity and beyond... CHAMPIONS!',
    ],
    loserPhrases: [
      'Hasta la vista, baby!',
      "You can't handle the truth!",
      "Here's looking at you, kid... better luck next time!",
      'I am inevitable... your loss!',
      "Frankly, my dear, I don't give a damn about your score!",
    ],
  },
  history: {
    name: 'History Frames',
    titleText: 'HISTORY',
    colors: {
      primary: '#C9A84C',
      primaryLight: '#E8D5A3',
      primaryDark: '#8B6914',
      accent: '#8B0000',
      accentDark: '#5C0000',
      secondary: '#4682B4',
      bgDark: '#0A0A0F',
      bgMid: '#0F1A2E',
      bgLight: '#162040',
      textLight: '#F5ECD7',
      textDark: '#0F1A2E',
    },
    categoryLabel: 'Moment',
    categoryLabelPlural: 'Moments',
    gameTitle: 'GUESS THE MOMENT',
    subtitle: 'THE ULTIMATE HISTORY GUESSING GAME',
    imageFolder: 'images_history',
    teamNames: [
      ['Patriots', 'Loyalists'],
      ['Union', 'Confederacy'],
      ['Federalists', 'Republicans'],
      ['Hamilton', 'Burr'],
      ['North', 'South'],
      ['Eagles', 'Redcoats'],
      ['Founders', 'Pioneers'],
      ['Liberty', 'Crown'],
    ],
    winnerPhrases: [
      'We the champions of this great nation!',
      'One giant leap for the winning team!',
      'Victory is yours — history will remember this!',
    ],
    loserPhrases: [
      'Those who cannot remember history are condemned to repeat it!',
      'Better luck in the next chapter of history!',
      'History is written by the victors... and that\'s not you!',
    ],
  },
}

export const CATEGORIES = {
  movies: {
    icon: '🎬',
    name: 'Movies',
    description: 'Guess the movie from the scene',
    color: '#FFD700',
    colorDark: '#DAA520',
    subcategories: {
      bollywood: { icon: null, iconImage: new URL('../assets/flag-india.svg', import.meta.url).href, name: 'Bollywood', themeKey: 'bollywood' },
      hollywood: { icon: '🎥', name: 'Hollywood', themeKey: 'hollywood' },
    },
  },
  history: {
    icon: '📚',
    name: 'History',
    description: 'Identify historical moments',
    color: '#C9A84C',
    colorDark: '#8B6914',
    subcategories: {
      american: { icon: '🦅', name: 'American', themeKey: 'history' },
    },
  },
  yolo: {
    icon: '🎲',
    name: 'YOLO',
    description: 'Random mix of everything!',
    color: '#FF6B6B',
    colorDark: '#CC4444',
    subcategories: null,
  },
}
